### ISSUE TITLE
[8.0] UPS Integration - How Much Funding Needed For Completion?

### ISSUE THREAD

**Issue by lukebranch** [aliomattux/omniship#5]
@aliomattux ,

I'm interested in getting UPS setup for one of our retail companies and I remembered you had this project going.

I can't contribute a huge amount of funding, but could perhaps organise a couple of hundred euros on my end if this will help with development of the module.

If funding will help would you mind putting together a list of features that the module will achieve (eg. printing shipping labels from backend, and organising shipments from backend of Odoo) so that I can try to get a budget organised to help partially fund the development?

I'd be happy to also spread the word on the community mailing lists and try to get more people interested in funding as well if this will help.

If you're open to funding to get the project completed please also let me know what license you plan to release it under (I assume it will stay open-source, although correct me if i'm wrong).

**Comment by aliomattux** [comment]
Hello,
Funding always helps and is how I am able to do all of the development I do. If you would like to fund certain development for this module that is certainly possible, but I must ask a few questions.

For which version do you need the module to work under. Currently my module only is officially supported in v8. I do not have any immediate plans to support v9 and would not be interested if that is your need.

What features exactly do you need?

The module is already in production use for a few clients. It has the ability now to print labels from the Odoo interface. It supports most domestic (United States) shipping method. The module can be adapted to be called by another model for automation or external automation.

90% of what I do is open source, and I prefer to work this way. I do not publish modules to the app store or charge for the code itself. Sometimes software developed does require it to be closed source, but that is certainly not the case here.

If you want to contact me directly, you can email me

**Comment by lukebranch** [comment]
@aliomattux ,

Thanks for the reply. I would need the module mainly for use with two retail websites. One in Hong Kong, one in the USA.

From the module i'd like to be able to print labels, book international shipping with UPS (for example ship from Hong Kong to the USA) and get tracking information within the Odoo interface.

It would be great if some sort of automation type features could be built into the e-commerce checkout process (eg. shopping cart quotes for different UPS shipping options), however this is not an absolute must at this point in time, and we can look into either paying your company to extend the module like this (if you're interested) or getting a third-party developer to build the e-commerce features we'd like later on down the line.

Regarding keeping it open-source, this is preferable for us as well, I just wanted to clarify.

I've installed this on my instances previously but have not yet managed to get it working. I'll give it another go over the weekend with the latest code to see if I can get things up and running so that I can test things out and look at the current features and where there may be features we'd like to see added if this is at all possible.

Can I reach you on the email address you're using on the mailing lists (OpenERP Master)?

**Comment by aliomattux** [comment]
Hello,

Yes I love open source. Selling closed source modules isn't my thing. You
said that you tried to get the module to work but couldn't. If you were
trying to do a shipment from Hong Kong to the US I would expect you to get
error as 1. I never tested international shipment and 2. Never tried to
ship from another country to the US.

To be clear, my module does not in any way support the ecommerce module
functionality of Odoo. If you need it to work with that, you would need to
find a developer for that as I am not interested in developing ecommerce
module features.

Another option for UPS is to do an ODBC integration. Then you can use all
of the features out of box. I have done this before.

I didnt see way to send private message in git. Email me the openerpmaster
email and ill give you my skype
